on: push

jobs:
  my-first-secret:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import os
          print(os.getenv("MY_SECRET"))
        shell: python
        env: 
          MY_SECRET: $${{ secrets.MY_SECRET }}
  # secrets:
    # runs-on: ubuntu-latest
    # steps:
    #   - run: echo $MY_SECRET
    # env: 
    #   MY_SECRET: ${{ secrets.MY_SECRET }}
